### ISSUE TITLE
Execute a read with no parameters

### ISSUE THREAD

**Issue by yazninja** [nDimensional/zig-sqlite#7]
I would want to read data as text which i would then pass to a json serializer

this is my statement
```zig
const query = "SELECT value FROM LocalStorage WHERE key = 'GameQualitySetting'";
        const json = struct { data: []const u8 };
        var stmt = try db.prepare(null, json, query);
        defer stmt.finalize();
```
as of now the docs doesn't specify a use case for no param execution of sql statements and compile errors in "Invlid Bind/Parameter type @Type('null')"

**Comment by joeltg** [comment]
Use an empty struct `struct {}` for statements without params :)

**Comment by joeltg** [comment]
You'll still have to call `try stmt.bind(.{})` with the empty params value `.{}`.

**Comment by joeltg** [comment]
A full example of reading data as text for you would look like this:

```
const Params = struct {};
const Result = struct { value: sqlite.Text };
const query = "SELECT value FROM LocalStorage WHERE key = 'GameQualitySetting'";
var stmt = try db.prepare(Params, Result, query);
defer stmt.finalize();

{
    try stmt.bind(.{});
    defer stmt.reset();
    if (try stmt.step()) |row| {
        const json = row.value.data; // json: []const u8
        // ...
    }
}
```
